plugins {
    id 'multiloader-common'
    id 'net.fabricmc.fabric-loom'
}

configurations {
    testCommonJava { canBeResolved = true }
    testCommonResources { canBeResolved = true }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation project(':fabric')

    compileOnly(project(':testmod-common')) {
        def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
    testCommonJava project(path: ':testmod-common', configuration: 'commonJava')
    testCommonResources project(path: ':testmod-common', configuration: 'commonResources')

    implementation "com.daqem.knot:knot-fabric:${project.knot_version}"
    implementation "com.daqem.uilib:uilib-fabric:${project.uilib_version}"
    implementation "com.daqem.yamlconfig:yamlconfig-fabric:${project.yamlconfig_version}"
    implementation "com.daqem.arc:arc-fabric:${project.arc_version}"
    implementation "com.daqem.itemrestrictions:itemrestrictions-fabric:${project.itemrestrictions_version}"
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.testCommonJava)
    source(configurations.testCommonJava)
}

processResources {
    dependsOn(configurations.testCommonResources)
    from(configurations.testCommonResources)
}

sourceSets {
    main {
        resources {
            srcDir project(':common').file('src/main/resources')
        }
    }
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Test Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Test Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}