//file:noinspection GroovyAssignabilityCheck
//file:noinspection DependencyNotationArgument
//file:noinspection GrDeprecatedAPIUsage
plugins {
    id 'com.github.johnrengelman.shadow'
    id "me.modmuss50.mod-publish-plugin" version "2.1.1"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    //noinspection GroovyAccessibility
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    modApi "dev.architectury:architectury-fabric:${project.architectury_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')

    modImplementation "com.daqem.uilib:uilib-fabric:${project.uilib_version}"
    modImplementation "com.daqem.yamlconfig:yamlconfig-fabric:${project.yamlconfig_version}"
    modImplementation "com.daqem.arc:arc-fabric:${project.arc_version}"
    modImplementation "com.daqem.itemrestrictions:itemrestrictions-fabric:${project.itemrestrictions_version}"
}

processResources {
    var replaceProperties = [
            "version": project.version,
            "mod_id": project.mod_id,
            "mod_name": project.mod_name,
            "mod_description": project.mod_description,
            "mod_author": project.mod_author,
            "mod_license": project.mod_license,
            "mod_website": project.mod_website,
            "mod_repository": project.mod_repository,

            "fabric_loader_version": project.fabric_loader_version,
            "fabric_api_version": project.fabric_api_version,
            "minecraft_version": project.minecraft_version,
            "architectury_version": project.architectury_version,
            "yamlconfig_version": project.yamlconfig_version,
            "arc_version": project.arc_version,
            "itemrestrictions_version": project.itemrestrictions_version,
            "uilib_version": project.uilib_version
    ]
    inputs.properties replaceProperties

    filesMatching(['fabric.mod.json']) {
        expand replaceProperties
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = "fabric-dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    archiveClassifier = "fabric"
}

remapSourcesJar {
    archiveClassifier = "fabric-sources"
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            groupId = rootProject.maven_group
            artifactId = rootProject.archives_base_name + "-fabric"
            from components.java
        }
    }

    repositories {
        maven {
            url = project.version.contains('-PR') ? 'https://maven.daqem.com/snapshots' : 'https://maven.daqem.com/releases'
            credentials {
                username = System.getenv("MAVEN_USER")
                password = System.getenv("MAVEN_PASS")
            }
        }
    }
}

publishMods {
    file = remapJar.archiveFile
    additionalFiles.from(remapSourcesJar.archiveFile)
    changelog = rootProject.file('changelog.md').text
    version = project.mod_version
    type = project.release_type == "release" ? STABLE : (project.release_type == "beta" ? BETA : ALPHA)
    modLoaders.add("fabric")

    curseforge {
        accessToken = System.getenv("CURSEFORGE_API_KEY")
        projectId = project.curse_forge_project_id
        minecraftVersions.addAll(project.supported_minecraft_versions.split(','))

        displayName = "$project.mod_name Fabric - $project.mod_version"

        // FIX: These two lines satisfy the new CurseForge requirement
        client = true
        server = true

        // Dependencies
        project.curseforge_dependencies.split(',').each { dep ->
            requires(dep.trim())
        }
    }

    modrinth {
        accessToken = System.getenv("MODRINTH_API_KEY")
        projectId = project.modrinth_project_id
        minecraftVersions.addAll(project.supported_minecraft_versions.split(','))

        displayName = "$project.mod_name Fabric - $project.mod_version"

        // Dependencies
        project.modrinth_dependencies.split(',').each { dep ->
            requires(dep.trim())
        }
    }
}