org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=false
java_version=25

# Project Info
group=com.daqem.jobsplus
version=21.2.0
mod_id=jobsplus
mod_name=Jobs+
mod_description=Adds 10 jobs with power-ups to Minecraft. You can also add your own!
mod_author=DAQEM
mod_license=Apache-2.0
mod_website=https://daqem.com/projects/jobsplus
mod_repository=https://github.com/DAQEM/JobsPlusRemastered

# Publishing
supported_minecraft_versions=26.2
release_type=release
curse_forge_project_id=916985
curse_forge_dependencies=knot,ui,yaml-config,arc,item-restrictions
modrinth_project_id=hxGLlCnq
modrinth_dependencies=knot,ui-lib,yaml-config,arc,item-restrictions

# Dependencies
minecraft_version=26.2
neo_form_version=26.2-2
knot_version=21.2.0
uilib_version=21.1.1
yamlconfig_version=21.1.0
arc_version=21.2.0
itemrestrictions_version=21.1.0

# Fabric
fabric_version=0.156.0+26.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.2.0.37-beta

