package me.daqem.jobsplus;

import net.minecraftforge.common.ForgeConfigSpec;

public class Config {

    public static final String CATEGORY_GENERAL = "general";
    public static final String CATEGORY_LEVEL_UP = "level_up";
    public static final String CATEGORY_CRAFTING = "crafting";
    public static final String CATEGORY_CRAFTING_TOOLS = "tools";
    public static final String CATEGORY_CRAFTING_TOOLS_MINER = "miner";
    public static final String CATEGORY_CRAFTING_TOOLS_DIGGER = "digger";
    public static final String CATEGORY_CRAFTING_TOOLS_LUMBERJACK = "lumberjack";
    public static final String CATEGORY_CRAFTING_TOOLS_FARMER = "farmer";
    public static final String CATEGORY_CRAFTING_TOOLS_HUNTER = "hunter";
    public static final String CATEGORY_CRAFTING_TOOLS_FISHERMAN = "fisherman";
    public static final String CATEGORY_CRAFTING_ARMOR = "armor";
    public static final String CATEGORY_CRAFTING_OTHER = "other";
    public static final String CATEGORY_CRAFTING_OTHER_ENCHANTER = "enchanter";
    public static final String CATEGORY_CRAFTING_OTHER_BUILDER = "builder";

    public static ForgeConfigSpec SERVER_CONFIG;

    //CATEGORY_LEVEL_UP
    public static ForgeConfigSpec.IntValue COINS_PER_LEVEL_UP;

    //CATEGORY_CRAFTING
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_EXP_JAR;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_EXPERIENCE_BOTTLE_TIER_1;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_EXPERIENCE_BOTTLE_TIER_2;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_EXPERIENCE_BOTTLE_TIER_3;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_EXPERIENCE_BOTTLE_TIER_4;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_EXPERIENCE_BOTTLE_TIER_5;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_EXPERIENCE_BOTTLE_TIER_6;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_EXP_JAR_TO_EXPERIENCE_BOTTLE;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_CURSE_BREAKER;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_REINFORCED_IRON_HELMET;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_REINFORCED_IRON_BOOTS;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_OBSIDIAN_HELMET;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_OBSIDIAN_BOOTS;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_REINFORCED_IRON_LEGGINGS;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_OBSIDIAN_LEGGINGS;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_REINFORCED_IRON_CHESTPLATE;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_REINFORCED_DIAMOND_HELMET;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_REINFORCED_DIAMOND_BOOTS;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_OBSIDIAN_CHESTPLATE;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_REINFORCED_DIAMOND_LEGGINGS;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_REINFORCED_NETHERITE_HELMET;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_REINFORCED_NETHERITE_BOOTS;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_REINFORCED_DIAMOND_CHESTPLATE;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_REINFORCED_NETHERITE_LEGGINGS;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_REINFORCED_NETHERITE_CHESTPLATE;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_HUNTER_WOOL;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_SMALL_BACKPACK;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_MEDIUM_BACKPACK;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_LARGE_BACKPACK;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_HUGE_BACKPACK;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_ENDER_BACKPACK;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_MINERS_HAMMER_LEVEL_1;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_MINERS_HAMMER_LEVEL_2;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_MINERS_HAMMER_LEVEL_3;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_MINERS_HAMMER_LEVEL_4;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_DIGGERS_EXCAVATOR_LEVEL_1;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_DIGGERS_EXCAVATOR_LEVEL_2;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_DIGGERS_EXCAVATOR_LEVEL_3;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_DIGGERS_EXCAVATOR_LEVEL_4;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_LUMBERJACK_AXE_LEVEL_1;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_LUMBERJACK_AXE_LEVEL_2;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_LUMBERJACK_AXE_LEVEL_3;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_LUMBERJACK_AXE_LEVEL_4;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_FARMERS_HOE_LEVEL_1;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_FARMERS_HOE_LEVEL_2;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_FARMERS_HOE_LEVEL_3;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_FARMERS_HOE_LEVEL_4;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_HUNTERS_SWORD_LEVEL_1;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_HUNTERS_SWORD_LEVEL_2;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_HUNTERS_SWORD_LEVEL_3;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_HUNTERS_SWORD_LEVEL_4;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_HUNTERS_BOW_LEVEL_1;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_HUNTERS_BOW_LEVEL_2;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_HUNTERS_BOW_LEVEL_3;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_HUNTERS_BOW_LEVEL_4;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_FISHERMANS_ROD_LEVEL_1;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_FISHERMANS_ROD_LEVEL_2;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_FISHERMANS_ROD_LEVEL_3;
    public static ForgeConfigSpec.IntValue REQUIRED_LEVEL_FISHERMANS_ROD_LEVEL_4;

    static {
        ForgeConfigSpec.Builder serverBuilder = new ForgeConfigSpec.Builder();
        serverBuilder.push(CATEGORY_GENERAL);
        serverBuilder.pop();
        serverBuilder.push(CATEGORY_LEVEL_UP);
        COINS_PER_LEVEL_UP = serverBuilder.comment("Amount of coins given to a player each time they level up a job.").defineInRange("coins_per_level_up", 1, 0, Integer.MAX_VALUE);
        serverBuilder.pop();
        serverBuilder.push(CATEGORY_CRAFTING);
        serverBuilder.push(CATEGORY_CRAFTING_TOOLS);
        serverBuilder.push(CATEGORY_CRAFTING_TOOLS_MINER);
        REQUIRED_LEVEL_MINERS_HAMMER_LEVEL_1 = serverBuilder.defineInRange("required_level_miners_hammer_level_1", 5, 0, 100);
        REQUIRED_LEVEL_MINERS_HAMMER_LEVEL_2 = serverBuilder.defineInRange("required_level_miners_hammer_level_2", 25, 0, 100);
        REQUIRED_LEVEL_MINERS_HAMMER_LEVEL_3 = serverBuilder.defineInRange("required_level_miners_hammer_level_3", 50, 0, 100);
        REQUIRED_LEVEL_MINERS_HAMMER_LEVEL_4 = serverBuilder.defineInRange("required_level_miners_hammer_level_4", 75, 0, 100);
        serverBuilder.pop();
        serverBuilder.push(CATEGORY_CRAFTING_TOOLS_DIGGER);
        REQUIRED_LEVEL_DIGGERS_EXCAVATOR_LEVEL_1 = serverBuilder.defineInRange("required_level_diggers_excavator_level_1", 5, 0, 100);
        REQUIRED_LEVEL_DIGGERS_EXCAVATOR_LEVEL_2 = serverBuilder.defineInRange("required_level_diggers_excavator_level_2", 25, 0, 100);
        REQUIRED_LEVEL_DIGGERS_EXCAVATOR_LEVEL_3 = serverBuilder.defineInRange("required_level_diggers_excavator_level_3", 50, 0, 100);
        REQUIRED_LEVEL_DIGGERS_EXCAVATOR_LEVEL_4 = serverBuilder.defineInRange("required_level_diggers_excavator_level_4", 75, 0, 100);
        serverBuilder.pop();
        serverBuilder.push(CATEGORY_CRAFTING_TOOLS_LUMBERJACK);
        REQUIRED_LEVEL_LUMBERJACK_AXE_LEVEL_1 = serverBuilder.defineInRange("required_level_lumberjack_axe_level_1", 5, 0, 100);
        REQUIRED_LEVEL_LUMBERJACK_AXE_LEVEL_2 = serverBuilder.defineInRange("required_level_lumberjack_axe_level_2", 25, 0, 100);
        REQUIRED_LEVEL_LUMBERJACK_AXE_LEVEL_3 = serverBuilder.defineInRange("required_level_lumberjack_axe_level_3", 50, 0, 100);
        REQUIRED_LEVEL_LUMBERJACK_AXE_LEVEL_4 = serverBuilder.defineInRange("required_level_lumberjack_axe_level_4", 75, 0, 100);
        serverBuilder.pop();
        serverBuilder.push(CATEGORY_CRAFTING_TOOLS_FARMER);
        REQUIRED_LEVEL_FARMERS_HOE_LEVEL_1 = serverBuilder.defineInRange("required_level_farmers_hoe_level_1", 5, 0, 100);
        REQUIRED_LEVEL_FARMERS_HOE_LEVEL_2 = serverBuilder.defineInRange("required_level_farmers_hoe_level_2", 25, 0, 100);
        REQUIRED_LEVEL_FARMERS_HOE_LEVEL_3 = serverBuilder.defineInRange("required_level_farmers_hoe_level_3", 50, 0, 100);
        REQUIRED_LEVEL_FARMERS_HOE_LEVEL_4 = serverBuilder.defineInRange("required_level_farmers_hoe_level_4", 75, 0, 100);
        serverBuilder.pop();
        serverBuilder.push(CATEGORY_CRAFTING_TOOLS_HUNTER);
        REQUIRED_LEVEL_HUNTERS_SWORD_LEVEL_1 = serverBuilder.defineInRange("required_level_hunters_sword_level_1", 5, 0, 100);
        REQUIRED_LEVEL_HUNTERS_SWORD_LEVEL_2 = serverBuilder.defineInRange("required_level_hunters_sword_level_2", 25, 0, 100);
        REQUIRED_LEVEL_HUNTERS_SWORD_LEVEL_3 = serverBuilder.defineInRange("required_level_hunters_sword_level_3", 50, 0, 100);
        REQUIRED_LEVEL_HUNTERS_SWORD_LEVEL_4 = serverBuilder.defineInRange("required_level_hunters_sword_level_4", 75, 0, 100);
        REQUIRED_LEVEL_HUNTERS_BOW_LEVEL_1 = serverBuilder.defineInRange("required_level_hunters_bow_level_1", 5, 0, 100);
        REQUIRED_LEVEL_HUNTERS_BOW_LEVEL_2 = serverBuilder.defineInRange("required_level_hunters_bow_level_2", 25, 0, 100);
        REQUIRED_LEVEL_HUNTERS_BOW_LEVEL_3 = serverBuilder.defineInRange("required_level_hunters_bow_level_3", 50, 0, 100);
        REQUIRED_LEVEL_HUNTERS_BOW_LEVEL_4 = serverBuilder.defineInRange("required_level_hunters_bow_level_4", 75, 0, 100);
        serverBuilder.pop();
        serverBuilder.push(CATEGORY_CRAFTING_TOOLS_FISHERMAN);
        REQUIRED_LEVEL_FISHERMANS_ROD_LEVEL_1 = serverBuilder.defineInRange("required_level_fishermans_rod_level_1", 5, 0, 100);
        REQUIRED_LEVEL_FISHERMANS_ROD_LEVEL_2 = serverBuilder.defineInRange("required_level_fishermans_rod_level_2", 25, 0, 100);
        REQUIRED_LEVEL_FISHERMANS_ROD_LEVEL_3 = serverBuilder.defineInRange("required_level_fishermans_rod_level_3", 50, 0, 100);
        REQUIRED_LEVEL_FISHERMANS_ROD_LEVEL_4 = serverBuilder.defineInRange("required_level_fishermans_rod_level_4", 75, 0, 100);
        serverBuilder.pop();
        serverBuilder.pop();
        serverBuilder.push(CATEGORY_CRAFTING_ARMOR);
        REQUIRED_LEVEL_REINFORCED_IRON_HELMET = serverBuilder.defineInRange("required_level_reinforced_iron_helmet", 1, 0, 100);
        REQUIRED_LEVEL_REINFORCED_IRON_CHESTPLATE = serverBuilder.defineInRange("required_level_reinforced_iron_chestplate", 10, 0, 100);
        REQUIRED_LEVEL_REINFORCED_IRON_LEGGINGS = serverBuilder.defineInRange("required_level_reinforced_iron_leggings", 5, 0, 100);
        REQUIRED_LEVEL_REINFORCED_IRON_BOOTS = serverBuilder.defineInRange("required_level_reinforced_iron_boots", 1, 0, 100);
        REQUIRED_LEVEL_OBSIDIAN_HELMET = serverBuilder.defineInRange("required_level_obsidian_helmet", 5, 0, 100);
        REQUIRED_LEVEL_OBSIDIAN_CHESTPLATE = serverBuilder.defineInRange("required_level_obsidian_chestplate", 20, 0, 100);
        REQUIRED_LEVEL_OBSIDIAN_LEGGINGS = serverBuilder.defineInRange("required_level_obsidian_leggings", 10, 0, 100);
        REQUIRED_LEVEL_OBSIDIAN_BOOTS = serverBuilder.defineInRange("required_level_obsidian_boots", 5, 0, 100);
        REQUIRED_LEVEL_REINFORCED_DIAMOND_HELMET = serverBuilder.defineInRange("required_level_reinforced_diamond_helmet", 20, 0, 100);
        REQUIRED_LEVEL_REINFORCED_DIAMOND_CHESTPLATE = serverBuilder.defineInRange("required_level_reinforced_diamond_chestplate", 50, 0, 100);
        REQUIRED_LEVEL_REINFORCED_DIAMOND_LEGGINGS = serverBuilder.defineInRange("required_level_reinforced_diamond_leggings", 35, 0, 100);
        REQUIRED_LEVEL_REINFORCED_DIAMOND_BOOTS = serverBuilder.defineInRange("required_level_reinforced_diamond_boots", 20, 0, 100);
        REQUIRED_LEVEL_REINFORCED_NETHERITE_HELMET = serverBuilder.defineInRange("required_level_reinforced_netherite_helmet", 50, 0, 100);
        REQUIRED_LEVEL_REINFORCED_NETHERITE_CHESTPLATE = serverBuilder.defineInRange("required_level_reinforced_netherite_chestplate", 100, 0, 100);
        REQUIRED_LEVEL_REINFORCED_NETHERITE_LEGGINGS = serverBuilder.defineInRange("required_level_reinforced_netherite_leggings", 75, 0, 100);
        REQUIRED_LEVEL_REINFORCED_NETHERITE_BOOTS = serverBuilder.defineInRange("required_level_reinforced_netherite_boots", 50, 0, 100);
        serverBuilder.pop();
        serverBuilder.push(CATEGORY_CRAFTING_OTHER);
        REQUIRED_LEVEL_HUNTER_WOOL = serverBuilder.defineInRange("required_level_hunter_wool", 1, 0, 100);
        serverBuilder.push(CATEGORY_CRAFTING_OTHER_ENCHANTER);
        REQUIRED_LEVEL_EXP_JAR = serverBuilder.defineInRange("required_level_exp_jar", 5, 0, 100);
        REQUIRED_LEVEL_CURSE_BREAKER = serverBuilder.defineInRange("required_level_curse_breaker", 10, 0, 100);
        REQUIRED_LEVEL_EXPERIENCE_BOTTLE_TIER_1 = serverBuilder.defineInRange("required_level_experience_bottle_tier_1", 10, 0, 100);
        REQUIRED_LEVEL_EXPERIENCE_BOTTLE_TIER_2 = serverBuilder.defineInRange("required_level_experience_bottle_tier_2", 20, 0, 100);
        REQUIRED_LEVEL_EXPERIENCE_BOTTLE_TIER_3 = serverBuilder.defineInRange("required_level_experience_bottle_tier_3", 35, 0, 100);
        REQUIRED_LEVEL_EXPERIENCE_BOTTLE_TIER_4 = serverBuilder.defineInRange("required_level_experience_bottle_tier_4", 50, 0, 100);
        REQUIRED_LEVEL_EXPERIENCE_BOTTLE_TIER_5 = serverBuilder.defineInRange("required_level_experience_bottle_tier_5", 75, 0, 100);
        REQUIRED_LEVEL_EXPERIENCE_BOTTLE_TIER_6 = serverBuilder.defineInRange("required_level_experience_bottle_tier_6", 100, 0, 100);
        REQUIRED_LEVEL_EXP_JAR_TO_EXPERIENCE_BOTTLE = serverBuilder.defineInRange("required_level_exp_jar_to_experience_bottle", 25, 0, 100);
        serverBuilder.pop();
        serverBuilder.push(CATEGORY_CRAFTING_OTHER_BUILDER);
        REQUIRED_LEVEL_SMALL_BACKPACK = serverBuilder.defineInRange("required_level_small_backpack", 5, 0, 100);
        REQUIRED_LEVEL_MEDIUM_BACKPACK = serverBuilder.defineInRange("required_level_medium_backpack", 15, 0, 100);
        REQUIRED_LEVEL_LARGE_BACKPACK = serverBuilder.defineInRange("required_level_large_backpack", 25, 0, 100);
        REQUIRED_LEVEL_HUGE_BACKPACK = serverBuilder.defineInRange("required_level_huge_backpack", 50, 0, 100);
        REQUIRED_LEVEL_ENDER_BACKPACK = serverBuilder.defineInRange("required_level_ender_backpack", 10, 0, 100);
        serverBuilder.pop();
        serverBuilder.pop();
        serverBuilder.pop();

        SERVER_CONFIG = serverBuilder.build();
    }

}
