//file:noinspection GroovyAssignabilityCheck
architectury {
    //noinspection GrUnresolvedAccess
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/jobsplus.accesswidener")
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modApi "dev.architectury:architectury:${project.architectury_version}"

    modImplementation "com.daqem.uilib:uilib-common:${project.uilib_version}"
    modImplementation "com.daqem.yamlconfig:yamlconfig-common:${project.yamlconfig_version}"
    modImplementation "com.daqem.arc:arc-common:${project.arc_version}"
    modImplementation "com.daqem.itemrestrictions:itemrestrictions-common:${project.itemrestrictions_version}"

    testImplementation "org.junit.jupiter:junit-jupiter-api:${project.jUnitVersion}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${project.jUnitVersion}"

}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            groupId = rootProject.maven_group
            artifactId = rootProject.archives_base_name + "-common"
            from components.java
        }
    }

    repositories {
        maven {
            url = project.version.contains('-PR') ? 'https://maven.daqem.com/snapshots' : 'https://maven.daqem.com/releases'
            credentials {
                username = System.getenv("MAVEN_USER")
                password = System.getenv("MAVEN_PASS")
            }
        }
    }
}

test {
    useJUnitPlatform()
}