modLoader = "javafml"
loaderVersion = "[1,)"
license = "Apache-2.0"

[[mods]]
modId = "jobsplus_test"
version = "1.0.0"
displayName = "JobsPlus Test Mod"
authors = "DAQEM"
description = '''
This is a test mod for JobsPlus.
'''
license = "Apache-2.0"